//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.25 at 09:44:49 PM MSK 
//


package by.kiselevich.xmlparser.entity.medicins;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Form.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Form">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="tablets"/>
 *     &lt;enumeration value="capsules"/>
 *     &lt;enumeration value="powder"/>
 *     &lt;enumeration value="drops"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Form")
@XmlEnum
public enum Form {

    @XmlEnumValue("tablets")
    TABLETS("tablets"),
    @XmlEnumValue("capsules")
    CAPSULES("capsules"),
    @XmlEnumValue("powder")
    POWDER("powder"),
    @XmlEnumValue("drops")
    DROPS("drops");
    private final String value;

    Form(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Form fromValue(String v) {
        for (Form c: Form.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
