//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.25 at 09:44:49 PM MSK 
//


package by.kiselevich.xmlparser.entity.medicins;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Group.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Group">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="antibiotics"/>
 *     &lt;enumeration value="painkillers"/>
 *     &lt;enumeration value="vitamins"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Group")
@XmlEnum
public enum Group {

    @XmlEnumValue("antibiotics")
    ANTIBIOTICS("antibiotics"),
    @XmlEnumValue("painkillers")
    PAINKILLERS("painkillers"),
    @XmlEnumValue("vitamins")
    VITAMINS("vitamins");
    private final String value;

    Group(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Group fromValue(String v) {
        for (Group c: Group.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
